# Generated by Django 4.2.7 on 2025-09-30 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="शीर्षक")),
                ("content", models.TextField(verbose_name="आशय")),
                (
                    "image_url",
                    models.URLField(blank=True, null=True, verbose_name="प्रतिमा URL"),
                ),
                (
                    "date_posted",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="प्रकाशन दिनांक"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="वैशिष्ट्यपूर्ण"),
                ),
            ],
            options={
                "verbose_name": "बातमी",
                "verbose_name_plural": "बातम्या",
                "db_table": "news",
                "ordering": ["-date_posted"],
            },
        ),
    ]
