# Generated by Django 4.2.7 on 2025-09-30 08:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="जिल्ह्याचे नाव")),
            ],
            options={
                "verbose_name": "जिल्हा",
                "verbose_name_plural": "जिल्हे",
                "db_table": "district",
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="विभागाचे नाव")),
            ],
            options={
                "verbose_name": "विभाग",
                "verbose_name_plural": "विभाग",
                "db_table": "division",
            },
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="गावाचे नाव")),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villages",
                        to="core.district",
                        verbose_name="जिल्हा",
                    ),
                ),
            ],
            options={
                "verbose_name": "गाव",
                "verbose_name_plural": "गावे",
                "db_table": "village",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="नाव")),
                ("surname", models.CharField(max_length=50, verbose_name="आडनाव")),
                (
                    "birth_year",
                    models.IntegerField(blank=True, null=True, verbose_name="जन्म वर्ष"),
                ),
                (
                    "reservation_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="आरक्षण क्रमांक"
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="संपर्क क्रमांक"
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="जोडलेला दिनांक"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="सत्यापित"),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        to="core.village",
                        verbose_name="गाव",
                    ),
                ),
            ],
            options={
                "verbose_name": "व्यक्ती",
                "verbose_name_plural": "लोक",
                "db_table": "person",
                "ordering": ["-date_added"],
            },
        ),
        migrations.AddField(
            model_name="district",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="core.division",
                verbose_name="विभाग",
            ),
        ),
    ]
