# Generated by Django 4.2.7 on 2025-09-30 08:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="पूर्ण नाव")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=15, verbose_name="फोन नंबर"),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("free", "फ्री"),
                            ("premium", "प्रीमियम"),
                            ("pro", "प्रो"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="सदस्यता प्रकार",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(default=False, verbose_name="ईमेल सत्यापित"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.village",
                        verbose_name="गाव",
                    ),
                ),
            ],
            options={
                "verbose_name": "वापरकर्ता",
                "verbose_name_plural": "वापरकर्ते",
                "db_table": "user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PremiumService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="सेवेचे नाव")),
                ("description", models.TextField(verbose_name="वर्णन")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="किंमत"
                    ),
                ),
                ("duration_days", models.IntegerField(verbose_name="कालावधी (दिवस)")),
                ("features", models.TextField(verbose_name="वैशिष्ट्ये")),
                ("is_active", models.BooleanField(default=True, verbose_name="सक्रिय")),
            ],
            options={
                "verbose_name": "प्रीमियम सेवा",
                "verbose_name_plural": "प्रीमियम सेवा",
                "db_table": "premium_service",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="व्यवहार आयडी"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="रक्कम"
                    ),
                ),
                ("service", models.CharField(max_length=50, verbose_name="सेवा")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("upi", "UPI"),
                            ("card", "कार्ड"),
                            ("netbanking", "नेट बँकिंग"),
                        ],
                        max_length=20,
                        verbose_name="पेमेंट पद्धत",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "प्रलंबित"),
                            ("success", "यशस्वी"),
                            ("failed", "अयशस्वी"),
                            ("refunded", "परतावा"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="स्थिती",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="तयार केले"
                    ),
                ),
                (
                    "date_processed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="प्रक्रिया केली"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="वापरकर्ता",
                    ),
                ),
            ],
            options={
                "verbose_name": "पेमेंट",
                "verbose_name_plural": "पेमेंट्स",
                "db_table": "payment",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="शीर्षक")),
                ("message", models.TextField(verbose_name="संदेश")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("info", "माहिती"),
                            ("success", "यश"),
                            ("warning", "चेतावणी"),
                            ("error", "त्रुटी"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="प्रकार",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("web", "वेब"), ("email", "ईमेल"), ("sms", "SMS")],
                        default="web",
                        max_length=20,
                        verbose_name="चॅनेल",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="वाचले")),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="तयार केले"
                    ),
                ),
                (
                    "date_sent",
                    models.DateTimeField(blank=True, null=True, verbose_name="पाठवले"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="वापरकर्ता",
                    ),
                ),
            ],
            options={
                "verbose_name": "सूचना",
                "verbose_name_plural": "सूचना",
                "db_table": "notification",
                "ordering": ["-date_created"],
            },
        ),
    ]
