# Generated by Django 4.2.7 on 2025-09-30 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="अर्ज क्रमांक"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "सबमिट केले"),
                            ("under_review", "तपासणी"),
                            ("approved", "मंजूर"),
                            ("rejected", "नाकारले"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="स्थिती",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "सामान्य"),
                            ("high", "उच्च"),
                            ("premium", "प्रीमियम"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="प्राधान्य",
                    ),
                ),
                (
                    "applicant_name",
                    models.CharField(max_length=100, verbose_name="अर्जदाराचे नाव"),
                ),
                (
                    "applicant_surname",
                    models.CharField(max_length=50, verbose_name="आडनाव"),
                ),
                (
                    "birth_year",
                    models.IntegerField(blank=True, null=True, verbose_name="जन्म वर्ष"),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="संपर्क क्रमांक"
                    ),
                ),
                (
                    "date_submitted",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="सबमिट दिनांक"
                    ),
                ),
                (
                    "estimated_completion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="अंदाजित पूर्णता"
                    ),
                ),
                (
                    "actual_completion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="वास्तविक पूर्णता"
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("gram_committee", "ग्राम समिती"),
                            ("taluka_committee", "तालुका समिती"),
                            ("scrutiny_committee", "छाननी समिती"),
                            ("final_approval", "अंतिम मंजुरी"),
                        ],
                        default="gram_committee",
                        max_length=50,
                        verbose_name="सध्याचा टप्पा",
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(default=20, verbose_name="प्रगती टक्केवारी"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="वापरकर्ता",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.village",
                        verbose_name="गाव",
                    ),
                ),
            ],
            options={
                "verbose_name": "अर्ज",
                "verbose_name_plural": "अर्ज",
                "db_table": "application",
                "ordering": ["-date_submitted"],
            },
        ),
        migrations.CreateModel(
            name="StatusUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.CharField(max_length=50, verbose_name="टप्पा")),
                ("status", models.CharField(max_length=20, verbose_name="स्थिती")),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="संदेश"),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="अपडेट करणारा",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="अपडेट दिनांक"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="applications.application",
                        verbose_name="अर्ज",
                    ),
                ),
            ],
            options={
                "verbose_name": "स्थिती अपडेट",
                "verbose_name_plural": "स्थिती अपडेट्स",
                "db_table": "status_update",
                "ordering": ["-date_updated"],
            },
        ),
    ]
